# Generated by Django 4.2.1 on 2023-07-25 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('recordId', models.AutoField(primary_key=True, serialize=False, verbose_name='Número de radicado')),
                ('recordDate', models.DateTimeField(auto_now=True)),
                ('typeId', models.CharField(max_length=4, verbose_name='Tipo de identificación')),
                ('numberId', models.CharField(max_length=30, verbose_name='Número de identificación')),
                ('firstName', models.CharField(max_length=100, verbose_name='Nombres')),
                ('lastName', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=25, verbose_name='Teléfono')),
                ('messageType', models.CharField(max_length=50, verbose_name='Tipo de mensaje')),
                ('area', models.CharField(max_length=50, verbose_name='Área de recepción')),
                ('contractNumber', models.CharField(max_length=30, verbose_name='Número de contrato')),
                ('documentDate', models.DateField(verbose_name='Fecha del documento')),
                ('subject', models.CharField(max_length=250, verbose_name='Asunto')),
                ('replyCheck', models.BooleanField(verbose_name='Respuesta requerida')),
            ],
        ),
        migrations.CreateModel(
            name='RecordLoggedModel',
            fields=[
                ('recordId', models.AutoField(primary_key=True, serialize=False, verbose_name='Número de radicado')),
                ('recordDate', models.DateTimeField(auto_now=True)),
                ('messageType', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de mensaje')),
                ('area', models.CharField(max_length=50, verbose_name='Área de recepción')),
                ('contractNumber', models.CharField(max_length=30, verbose_name='Número de contrato')),
                ('documentDate', models.DateField(verbose_name='Fecha del documento')),
                ('documentType', models.CharField(default=None, max_length=50, verbose_name='Tipo de documento')),
                ('subject', models.CharField(max_length=250, verbose_name='Asunto')),
                ('replyCheck', models.BooleanField(verbose_name='Respuesta requerida')),
                ('file', models.FileField(default=None, upload_to='file_system')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecordFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namefile', models.CharField(max_length=255, verbose_name='Nombre de archivo')),
                ('filetype', models.CharField(max_length=100, verbose_name='Tipo de archivo')),
                ('file', models.TextField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_management.record')),
            ],
        ),
    ]
