# Generated by Django 4.2.1 on 2023-08-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0003_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
