# Generated by Django 4.2.1 on 2023-08-01 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userprofile_typeid_userprofile_taxnumbertype_and_more'),
        ('record_management', '0004_delete_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordMngExtraFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extrafield1', models.CharField(max_length=100, verbose_name='Campo adicional 1')),
                ('extrafield2', models.CharField(max_length=100, verbose_name='Campo adicional 2')),
                ('extrafield3', models.CharField(max_length=100, verbose_name='Campo adicional 3')),
                ('extrafield4', models.CharField(max_length=100, verbose_name='Campo adicional 4')),
                ('extrafield5', models.CharField(max_length=100, verbose_name='Campo adicional 5')),
                ('extrafield6', models.CharField(max_length=100, verbose_name='Campo adicional 6')),
                ('extrafield7', models.CharField(max_length=100, verbose_name='Campo adicional 7')),
                ('extrafield8', models.CharField(max_length=100, verbose_name='Campo adicional 8')),
                ('extrafield9', models.CharField(max_length=100, verbose_name='Campo adicional 9')),
                ('extrafield10', models.CharField(max_length=100, verbose_name='Campo adicional 10')),
                ('companyid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'verbose_name': 'Gestor Documental - campo adicional',
                'verbose_name_plural': 'Gestor Documental -  campos adicionales',
            },
        ),
        migrations.CreateModel(
            name='RecordExtraFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extrafield1', models.CharField(max_length=100, verbose_name='Campo adicional 1')),
                ('extrafield2', models.CharField(max_length=100, verbose_name='Campo adicional 2')),
                ('extrafield3', models.CharField(max_length=100, verbose_name='Campo adicional 3')),
                ('extrafield4', models.CharField(max_length=100, verbose_name='Campo adicional 4')),
                ('extrafield5', models.CharField(max_length=100, verbose_name='Campo adicional 5')),
                ('extrafield6', models.CharField(max_length=100, verbose_name='Campo adicional 6')),
                ('extrafield7', models.CharField(max_length=100, verbose_name='Campo adicional 7')),
                ('extrafield8', models.CharField(max_length=100, verbose_name='Campo adicional 8')),
                ('extrafield9', models.CharField(max_length=100, verbose_name='Campo adicional 9')),
                ('extrafield10', models.CharField(max_length=100, verbose_name='Campo adicional 10')),
                ('companyid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
            options={
                'verbose_name': 'Formulario - campo adicional',
                'verbose_name_plural': 'Formulario - campos adicionales',
            },
        ),
    ]
