# Generated by Django 4.2.1 on 2023-08-01 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userprofile_typeid_userprofile_taxnumbertype_and_more'),
        ('record_management', '0005_recordmngextrafields_recordextrafields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordextrafields',
            name='companyid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='recordextrafields',
            name='extrafield1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 1'),
        ),
        migrations.AlterField(
            model_name='recordextrafields',
            name='extrafield10',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 10'),
        ),
        migrations.AlterField(
            model_name='recordextrafields',
            name='extrafield2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 2'),
        ),
        migrations.AlterField(
            model_name='recordextrafields',
            name='extrafield3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 3'),
        ),
        migrations.AlterField(
            model_name='recordextrafields',
            name='extrafield4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 4'),
        ),
        migrations.AlterField(
            model_name='recordextrafields',
            name='extrafield5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 5'),
        ),
        migrations.AlterField(
            model_name='recordextrafields',
            name='extrafield6',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 6'),
        ),
        migrations.AlterField(
            model_name='recordextrafields',
            name='extrafield7',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 7'),
        ),
        migrations.AlterField(
            model_name='recordextrafields',
            name='extrafield8',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 8'),
        ),
        migrations.AlterField(
            model_name='recordextrafields',
            name='extrafield9',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 9'),
        ),
        migrations.AlterField(
            model_name='recordmngextrafields',
            name='companyid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recordmngextrafields',
            name='extrafield1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 1'),
        ),
        migrations.AlterField(
            model_name='recordmngextrafields',
            name='extrafield10',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 10'),
        ),
        migrations.AlterField(
            model_name='recordmngextrafields',
            name='extrafield2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 2'),
        ),
        migrations.AlterField(
            model_name='recordmngextrafields',
            name='extrafield3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 3'),
        ),
        migrations.AlterField(
            model_name='recordmngextrafields',
            name='extrafield4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 4'),
        ),
        migrations.AlterField(
            model_name='recordmngextrafields',
            name='extrafield5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 5'),
        ),
        migrations.AlterField(
            model_name='recordmngextrafields',
            name='extrafield6',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 6'),
        ),
        migrations.AlterField(
            model_name='recordmngextrafields',
            name='extrafield7',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 7'),
        ),
        migrations.AlterField(
            model_name='recordmngextrafields',
            name='extrafield8',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 8'),
        ),
        migrations.AlterField(
            model_name='recordmngextrafields',
            name='extrafield9',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 9'),
        ),
    ]
