# Generated by Django 4.2.1 on 2023-08-02 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('record_management', '0006_alter_recordextrafields_companyid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='userOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RecordLoggedModel',
        ),
    ]
