# Generated by Django 4.2.1 on 2023-08-14 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('record_management', '0007_alter_record_userowner_delete_recordloggedmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='userOwner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL),
        ),
    ]
