# Generated by Django 4.2.1 on 2023-08-14 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0008_alter_record_userowner'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='record',
            table='mvnt_record',
        ),
        migrations.AlterModelTable(
            name='recordextrafields',
            table='mvnt_recordextrafields',
        ),
        migrations.AlterModelTable(
            name='recordfile',
            table='mvnt_recordfile',
        ),
        migrations.AlterModelTable(
            name='recordmngextrafields',
            table='mvnt_recordmngextrafields',
        ),
    ]
