# Generated by Django 4.2.1 on 2023-08-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0009_alter_record_table_alter_recordextrafields_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'Registro', 'verbose_name_plural': 'Registros'},
        ),
        migrations.AlterModelOptions(
            name='recordfile',
            options={'verbose_name': 'Archivo de registro', 'verbose_name_plural': 'Archivos de registro'},
        ),
    ]
