# Generated by Django 4.2.1 on 2023-08-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0010_alter_record_options_alter_recordfile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='phone',
        ),
        migrations.AddField(
            model_name='record',
            name='contactperson',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Persona de contacto'),
        ),
        migrations.AlterField(
            model_name='record',
            name='subject',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Asunto'),
        ),
    ]
