# Generated by Django 4.2.1 on 2023-08-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0012_remove_record_subject_record_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='contractNumber',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de contrato'),
        ),
    ]
