# Generated by Django 4.2.1 on 2023-09-14 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_companyid_userprofile_company_and_more'),
        ('record_management', '0013_alter_record_contractnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='subject',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Asunto'),
        ),
        migrations.CreateModel(
            name='RecordType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='Código Tipo de correspondencia')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción de Tipo de correspondencia')),
                ('companyid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Tipo de correspondencia',
                'verbose_name_plural': 'Tipos de correspondencia',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='Código Tipo de documento')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción de Tipo de documento')),
                ('recordtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_management.recordtype', verbose_name='Tipo de correspondencia')),
            ],
            options={
                'verbose_name': 'Tipo documental',
                'verbose_name_plural': 'Tipos documentales',
            },
        ),
        migrations.CreateModel(
            name='DocumentSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='Código de asunto')),
                ('description', models.CharField(max_length=100, verbose_name='Descripción de asunto')),
                ('documenttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record_management.documenttype', verbose_name='Tipo de documento')),
            ],
            options={
                'verbose_name': 'Tipo de asunto',
                'verbose_name_plural': 'Tipos de asuntos',
            },
        ),
    ]
