# Generated by Django 4.2.1 on 2023-09-29 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_profile_taxnumber_remove_profile_typeid_and_more'),
        ('record_management', '0014_record_subject_recordtype_documenttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='companyid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='record',
            name='documentSubject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='record_management.documentsubjects', verbose_name='Tipo de asunto'),
        ),
        migrations.AddField(
            model_name='record',
            name='documentType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='record_management.documenttype', verbose_name='Tipo documental'),
        ),
        migrations.AddField(
            model_name='record',
            name='extrafield1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 1'),
        ),
        migrations.AddField(
            model_name='record',
            name='extrafield10',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 10'),
        ),
        migrations.AddField(
            model_name='record',
            name='extrafield2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 2'),
        ),
        migrations.AddField(
            model_name='record',
            name='extrafield3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 3'),
        ),
        migrations.AddField(
            model_name='record',
            name='extrafield4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 4'),
        ),
        migrations.AddField(
            model_name='record',
            name='extrafield5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 5'),
        ),
        migrations.AddField(
            model_name='record',
            name='extrafield6',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 6'),
        ),
        migrations.AddField(
            model_name='record',
            name='extrafield7',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 7'),
        ),
        migrations.AddField(
            model_name='record',
            name='extrafield8',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 8'),
        ),
        migrations.AddField(
            model_name='record',
            name='extrafield9',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional 9'),
        ),
        migrations.AddField(
            model_name='record',
            name='filingDate',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de radicado'),
        ),
        migrations.AddField(
            model_name='record',
            name='filingNumber',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de radicado'),
        ),
        migrations.AddField(
            model_name='record',
            name='mngextrafield1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional mng 1'),
        ),
        migrations.AddField(
            model_name='record',
            name='mngextrafield10',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional mng 10'),
        ),
        migrations.AddField(
            model_name='record',
            name='mngextrafield2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional mng 2'),
        ),
        migrations.AddField(
            model_name='record',
            name='mngextrafield3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional mng 3'),
        ),
        migrations.AddField(
            model_name='record',
            name='mngextrafield4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional mng 4'),
        ),
        migrations.AddField(
            model_name='record',
            name='mngextrafield5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional mng 5'),
        ),
        migrations.AddField(
            model_name='record',
            name='mngextrafield6',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional mng 6'),
        ),
        migrations.AddField(
            model_name='record',
            name='mngextrafield7',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional mng 7'),
        ),
        migrations.AddField(
            model_name='record',
            name='mngextrafield8',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional mng 8'),
        ),
        migrations.AddField(
            model_name='record',
            name='mngextrafield9',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Campo adicional mng 9'),
        ),
        migrations.AddField(
            model_name='record',
            name='recordType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='record_management.recordtype', verbose_name='Tipo de correspondencia'),
        ),
    ]
