# Generated by Django 4.2.1 on 2023-10-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_management', '0015_record_companyid_record_documentsubject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
    ]
