# Generated by Django 4.2.1 on 2023-08-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_idtype_idtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idtype',
            options={'verbose_name': 'Tipo de identificación', 'verbose_name_plural': 'Tipos de identificación'},
        ),
    ]
