# Generated by Django 4.2.1 on 2023-08-01 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_idtype_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyid', models.CharField(max_length=20)),
                ('companyname', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='typeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_type', to='accounts.idtype', verbose_name='Tipo de identificación'),
        ),
    ]
