# Generated by Django 4.2.1 on 2023-08-01 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company_alter_userprofile_typeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='companyid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='companyid',
            field=models.CharField(max_length=20, verbose_name='ID Empresa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='companyname',
            field=models.CharField(max_length=250, verbose_name='Nombre de Empresa'),
        ),
    ]
