# Generated by Django 4.2.1 on 2023-08-01 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_companyid_alter_company_companyid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='companyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
    ]
