# Generated by Django 4.2.1 on 2023-08-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofile_companyid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='typeId',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='taxNumberType',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('NIT', 'Número de Identificación Tributaria')], default='CC', max_length=30, verbose_name='Tipo de identificación'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='IDtype',
        ),
    ]
