# Generated by Django 4.2.1 on 2023-08-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userprofile_typeid_userprofile_taxnumbertype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_document_manager',
            field=models.BooleanField(default=False, verbose_name='¿Es Gestor Documental?'),
        ),
    ]
