# Generated by Django 4.2.1 on 2023-08-14 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_is_document_manager'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='mvnt_company',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='mvnt_userprofile',
        ),
    ]
