# Generated by Django 4.2.1 on 2023-09-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_userprofile_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='companyid',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='numberId',
            new_name='identificationNumber',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='garzonf@gmail.com', max_length=100, verbose_name='Correo electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='garzonf', max_length=100, verbose_name='Nombre de usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_document_manager',
            field=models.BooleanField(default=False, verbose_name='¿Es Gestor Documental'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='taxNumberType',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('NIT', 'Número de Identificación Tributaria')], max_length=3, verbose_name='Tipo de identificación'),
        ),
    ]
