# Generated by Django 4.2.1 on 2023-09-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_companyid_userprofile_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Activado'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_document_manager',
            field=models.BooleanField(default=False, verbose_name='¿Es Gestor Documental?'),
        ),
    ]
