# Generated by Django 4.2.1 on 2023-09-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_userprofile_phone_remove_userprofile_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_active',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='garzonf', max_length=100, verbose_name='Nombre de usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_document_manager',
            field=models.BooleanField(default=False, verbose_name='¿Es Gestor Documental'),
        ),
    ]
