# Generated by Django 4.2.1 on 2023-09-17 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0014_remove_userprofile_is_active_userprofile_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxnumber', models.CharField(max_length=20, verbose_name='NIT')),
                ('typeid', models.CharField(blank=True, max_length=4, null=True)),
                ('is_document_manager', models.BooleanField(default=False, verbose_name='Gestor Documental')),
                ('is_active', models.BooleanField(default=False, verbose_name='Usuario activado')),
                ('companyid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
                'db_table': 'mvnt_profile',
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
