# Generated by Django 4.2.1 on 2023-09-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='taxnumber',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='typeid',
        ),
        migrations.AddField(
            model_name='profile',
            name='numberId',
            field=models.CharField(default='1', max_length=30, verbose_name='Número de identificación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='taxNumberType',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('NIT', 'Número de Identificación Tributaria')], default=1, max_length=30, verbose_name='Tipo de identificación'),
            preserve_default=False,
        ),
    ]
